Fix Illegal Op permissions caused by exception
promcteam/BossShopPro pull request #49
Opened 2024-02-20 03:01 UTC by Lumine1909

When execute opcommand cause exception, the op permission WON'T be reset.

2024-02-20 15:21 UTC, Travja requested changes

2024-02-20 15:21 UTC, Travja commented on src/main/java/org/black_ixx/bossshop/core/rewards/BSRewardTypePlayerCommandOp.java
> +                p.setOp(false);
Nice catch. Let's set the OP to false in a `finally` block and add just a little bit if logging to the catch to explain what happened.

2024-02-21 20:40 UTC, Lumine1909 commented
Thanks for your suggestion.
Is it better now? :-)

2024-02-21 23:31 UTC, Travja approved these changes

2024-02-21 23:31 UTC, merged