add two condition types
promcteam/BossShopPro pull request #9
Opened 2022-12-03 04:28 UTC by lijinhong11

2022-12-03 17:12 UTC, Travja requested changes

2022-12-03 17:12 UTC, Travja commented on src/main/java/org/black_ixx/bossshop/core/conditions/BSConditionTypeClientVersion.java
> +        CraftPlayer craftPlayer = (CraftPlayer) player;
We really can't be using version dependent NMS classes like this. If we want to use NMS, we're going to need to use reflection.

2022-12-03 17:12 UTC, Travja commented on src/main/java/org/black_ixx/bossshop/managers/config/ConfigKeyCompleter.java
> +        try {f2 = File.createTempFile("en-US-lang-cache","yml");//make cache
Can we please change this back so it is consistent with en_us.yml a couple lines earlier?

2022-12-03 17:12 UTC, Travja commented on src/main/java/org/black_ixx/bossshop/misc/ClassAndVerTools.java
> +    public static boolean isHighThanOrEquals(int i){
A better name could be `isGreaterThan`

2022-12-04 00:39 UTC, lijinhong11 commented
Sorry I can use NMS. Can you help me?

2022-12-04 02:03 UTC, Travja commented
Is there any reason in particular that we need the player's client version anyway?

2022-12-06 10:54 UTC, closed without merging